---
openapi: 3.0.1
info:
  title: Lekki Properties API by TS
  version: v1
paths:
  '/api/v1/properties':
    get:
      summary: list properties
      responses:
        '200':
          description: successful
    post:
      summary: create property
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                property_address:
                  type: string
                property_type:
                  type: string
                bathrooms:
                  type: integer
                bedrooms:
                  type: integer
                sitting_rooms:
                  type: integer
                toilets:
                  type: integer
                kitchens:
                  type: integer
                owner:
                  type: string
                description:
                  type: string
                valid_from:
                  type: string
                  format: date
                valid_to:
                  type: string
                  format: date
              required:
                - property_address
                - property_type
                - valid_from
                - valid_to
                - description
                - owner
                - kitchens
                - toilets
                - bathrooms
                - bedrooms
                - sitting_rooms
  '/api/v1/properties/{id}':
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show property
      responses:
        '200':
          description: successful
    put:
      summary: update property
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bathrooms:
                  type: integer
                bedrooms:
                  type: integer
                sitting_rooms:
                  type: integer
                toilets:
                  type: integer
                kitchens:
                  type: integer
                description:
                  type: string
                valid_to:
                  type: string
                  format: date
    delete:
      summary: delete property
      responses:
        '200':
          description: successful
  '/api/v1/properties/owner/{owner}':
    parameters:
      - name: owner
        in: path
        description: owner
        required: true
        schema:
          type: string
    get:
      summary: properties_by_owner property
      responses:
        '200':
          description: successful
  '/api/v1/properties/address/{address}':
    parameters:
      - name: address
        in: path
        description: address
        required: true
        schema:
          type: string
    get:
      summary: find_by_address property
      responses:
        '200':
          description: successful
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: property-klky.onrender.com
