---
openapi: 3.0.1
info:
  title: Lekki Properties API
  version: v1
paths:
  "/properties":
    get:
      summary: list properties
      responses:
        '200':
          description: successful
    post:
      summary: create property
      responses:
        '200':
          description: successful
  "/properties/new":
    get:
      summary: new property
      responses:
        '200':
          description: successful
  "/properties/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit property
      responses:
        '200':
          description: successful
  "/properties/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show property
      responses:
        '200':
          description: successful
    patch:
      summary: update property
      responses:
        '200':
          description: successful
    put:
      summary: update property
      responses:
        '200':
          description: successful
    delete:
      summary: delete property
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3001
