---
openapi: 3.0.1
info:
  title: Lekki Properties API
  version: v1
paths:
  "/api/v1/properties":
    get:
      summary: list properties
      responses:
        '200':
          description: successful
    post:
      summary: create property
      responses:
        '200':
          description: successful
  "/api/v1/properties/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show property
      responses:
        '200':
          description: successful
    patch:
      summary: update property
      responses:
        '200':
          description: successful
    put:
      summary: update property
      responses:
        '200':
          description: successful
    delete:
      summary: delete property
      responses:
        '200':
          description: successful
  "/api/v1/properties/owner/{owner}":
    parameters:
    - name: owner
      in: path
      description: owner
      required: true
      schema:
        type: string
    get:
      summary: properties_by_owner property
      responses:
        '200':
          description: successful
  "/api/v1/properties/address/{address}":
    parameters:
    - name: address
      in: path
      description: address
      required: true
      schema:
        type: string
    get:
      summary: find_by_address property
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
