---
openapi: 3.0.1
info:
  title: Lekki Properties API Documentation
  version: v2
  description: This is the API documentation for the Lekki Properties API
paths:
  "/api/v1/properties":
    post:
      summary: Creates a property
      tags:
      - Properties
      parameters: []
      responses:
        '201':
          description: property created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                property_address:
                  type: string
                property_type:
                  type: string
                bedrooms:
                  type: integer
                sitting_rooms:
                  type: integer
                kitchens:
                  type: integer
                bathrooms:
                  type: integer
                toilets:
                  type: integer
                owner:
                  type: string
                description:
                  type: string
                valid_from:
                  type: string
                  format: date-time
                valid_to:
                  type: string
                  format: date-time
              required:
              - property_address
              - property_type
              - bedrooms
              - sitting_rooms
              - kitchens
              - bathrooms
              - toilets
              - owner
              - description
              - valid_from
              - valid_to
    get:
      summary: Retrieves properties
      tags:
      - Properties
      parameters:
      - name: owner
        in: query
        description: Owner of the properties
        schema:
          type: string
      - name: bedrooms
        in: query
        description: Number of bedrooms in the properties
        schema:
          type: integer
      - name: bathrooms
        in: query
        description: Number of bathrooms in the properties
        schema:
          type: integer
      - name: address
        in: query
        description: Address of the properties
        schema:
          type: string
      responses:
        '200':
          description: properties found
        '404':
          description: properties not found
  "/api/v1/properties/{id}":
    get:
      summary: Retrieves a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: property found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  property_address:
                    type: string
                  property_type:
                    type: string
                  bedrooms:
                    type: integer
                  sitting_rooms:
                    type: integer
                  kitchens:
                    type: integer
                  bathrooms:
                    type: integer
                  toilets:
                    type: integer
                  owner:
                    type: string
                  description:
                    type: string
                  valid_from:
                    type: string
                    format: date-time
                  valid_to:
                    type: string
                    format: date-time
                required:
                - id
                - property_address
                - property_type
                - bedrooms
                - sitting_rooms
                - kitchens
                - bathrooms
                - toilets
                - owner
                - description
                - valid_from
                - valid_to
        '404':
          description: property not found
    put:
      summary: Updates a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: property updated
        '404':
          description: property not found
    delete:
      summary: Deletes a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: property deleted
        '404':
          description: property not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: property-klky.onrender.com
