---
openapi: 3.0.1
info:
  title: Lekki Properties API
  version: v2
paths:
  "/api/v1/properties":
    post:
      summary: Creates a property
      tags:
      - Properties
      parameters: []
      responses:
        '201':
          description: property created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                property_type:
                  type: string
                num_bedrooms:
                  type: integer
                num_sitting_rooms:
                  type: integer
                num_kitchens:
                  type: integer
                num_bathrooms:
                  type: integer
                num_toilets:
                  type: integer
                owner:
                  type: string
                description:
                  type: string
                valid_from:
                  type: string
                  format: date-time
                valid_to:
                  type: string
                  format: date-time
              required:
              - address
              - property_type
              - num_bedrooms
              - num_sitting_rooms
              - num_kitchens
              - num_bathrooms
              - num_toilets
              - owner
              - description
              - valid_from
              - valid_to
    get:
      summary: Retrieves properties
      tags:
      - Properties
      parameters:
      - name: owner
        in: query
        description: Owner of the properties
        schema:
          type: string
      - name: num_bedrooms
        in: query
        description: Number of bedrooms in the properties
        schema:
          type: integer
      - name: num_bathrooms
        in: query
        description: Number of bathrooms in the properties
        schema:
          type: integer
      - name: address
        in: query
        description: Address of the properties
        schema:
          type: string
      responses:
        '200':
          description: properties found
        '404':
          description: properties not found
  "/api/v1/properties/{id}":
    get:
      summary: Retrieves a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: property found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  address:
                    type: string
                  property_type:
                    type: string
                  num_bedrooms:
                    type: integer
                  num_sitting_rooms:
                    type: integer
                  num_kitchens:
                    type: integer
                  num_bathrooms:
                    type: integer
                  num_toilets:
                    type: integer
                  owner:
                    type: string
                  description:
                    type: string
                  valid_from:
                    type: string
                    format: date-time
                  valid_to:
                    type: string
                    format: date-time
                required:
                - id
                - address
                - property_type
                - num_bedrooms
                - num_sitting_rooms
                - num_kitchens
                - num_bathrooms
                - num_toilets
                - owner
                - description
                - valid_from
                - valid_to
        '404':
          description: property not found
    put:
      summary: Updates a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: property updated
        '404':
          description: property not found
    delete:
      summary: Deletes a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: property deleted
        '404':
          description: property not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: property-klky.onrender.com
