---
openapi: 3.0.1
info:
  title: Lekki Properties API Documentation
  version: v2
  description: This is the API documentation for the Lekki Properties API
  contact:
    email: sulaymantaofiq@gmail.com

paths:
  "/api/v1/properties":
    post:
      summary: Creates a property
      tags:
      - Properties
      parameters: []
      responses:
        '201':
          description: property created
        '422':
          description: invalid request
        '400':
          description: invalid parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                property_address:
                  type: string
                property_type:
                  type: string
                bedrooms:
                  type: integer
                sitting_rooms:
                  type: integer
                kitchens:
                  type: integer
                bathrooms:
                  type: integer
                toilets:
                  type: integer
                owner:
                  type: string
                description:
                  type: string
                valid_from:
                  type: string
                  format: date-time
                valid_to:
                  type: string
                  format: date-time
              required:
              - property_address
              - property_type
              - bedrooms
              - sitting_rooms
              - kitchens
              - bathrooms
              - toilets
              - owner
              - description
              - valid_from
              - valid_to
    get:
      summary: Retrieves properties
      tags:
      - Properties
      parameters:
      - name: owner
        in: query
        description: Owner of the properties
        schema:
          type: string
      - name: bedrooms
        in: query
        description: Number of bedrooms in the properties
        schema:
          type: integer
      - name: bathrooms
        in: query
        description: Number of bathrooms in the properties
        schema:
          type: integer
      - name: address
        in: query
        description: Address of the properties
        schema:
          type: string
      responses:
        '200':
          description: properties found
        '404':
          description: properties not found

  "/api/v1/properties/{id}":
    get:
      summary: Retrieves a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: property found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  property_address:
                    type: string
                  property_type:
                    type: string
                  bedrooms:
                    type: integer
                  sitting_rooms:
                    type: integer
                  kitchens:
                    type: integer
                  bathrooms:
                    type: integer
                  toilets:
                    type: integer
                  owner:
                    type: string
                  description:
                    type: string
                  valid_from:
                    type: string
                    format: date-time
                  valid_to:
                    type: string
                    format: date-time
                required:
                - id
                - property_address
                - property_type
                - bedrooms
                - sitting_rooms
                - kitchens
                - bathrooms
                - toilets
                - owner
                - description
                - valid_from
                - valid_to
        '404':
          description: property not found

  "/api/v1/properties/owners/{owner}":
    parameters:
      - in: path
        name: owner
        required: true
        description: Owner name
        schema:
          type: string
    get:
      summary: Retrieve multiple properties for a given owner
      tags:
        - Properties
      responses:
        '200':
          description: OK
        '404':
          description: Not Found

  "/api/v1/properties/addresses/{address}":
    parameters:
      - in: path
        name: address
        required: true
        description: Property address
        schema:
          type: string
    get:
      summary: Get property(s) by address
      tags:
        - Properties
      responses:
        '200':
          description: OK
        '404':
          description: Not Found

  "/api/v1/properties/filter/{property}":
    parameters:
    - name: owner
      in: query
      description: Owner of the property
      schema:
        type: string
    - name: property_type
      in: query
      description: Type of the property
      schema:
        type: string
    - name: bedrooms
      in: query
      description: Number of bedrooms
      schema:
        type: integer
    - name: sitting_rooms
      in: query
      description: Number of sitting rooms
      schema:
        type: integer
    - name: kitchens
      in: query
      description: Number of kitchens
      schema:
        type: integer
    - name: bathrooms
      in: query
      description: Number of bathrooms
      schema:
        type: integer
    - name: toilets
      in: query
      description: Number of toilets
      schema:
        type: integer
    - name: valid_to
      in: query
      format: date
      description: Validity date of the property
      schema:
        type: string
    get:
      summary: Retrieve multiple properties using additional filters
      responses:
        '200':
          description: successful
        '404':
          description: Not Found

  "/api/v1/properties/{id}":
    put:
      summary: Updates a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: property updated
        '404':
          description: property not found
    delete:
      summary: Deletes a property
      tags:
      - Properties
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: property deleted
        '404':
          description: property not found

components:
  schemas:
    Property:
      type: object
      properties:
        id:
          type: integer
        property_address:
          type: string
        property_type:
          type: string
        bedrooms:
          type: integer
        sitting_rooms:
          type: integer
        kitchens:
          type: integer
        bathrooms:
          type: integer
        toilets:
          type: integer
        owner:
          type: string
        description:
          type: string
        valid_from:
          type: string
          format: date-time
        valid_to:
          type: string
          format: date-time

servers:
- url: https://property-klky.onrender.com
