default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: properties_app

test:
  <<: *default
  database: property_app_test
