
default: &default
  adapter: postgresql
  encoding: unicode
  # host: db
  username: postgres
  password: password

development:
  <<: *default
  database: property_management_app

test:
  <<: *default
  database: property_management_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
